name: Dependency Review on Push

on:
  push:
    branches:
      - '**' # This will match all branches

permissions:
  contents: read
  pull-requests: write # Required for `comment-summary-in-pr`

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      # Step 2: Get the default branch (e.g., main or master)
      - name: Get default branch
        id: default-branch
        run: |
          DEFAULT_BRANCH=$(curl -s -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }} | jq -r '.default_branch')
          echo "Default branch: $DEFAULT_BRANCH"
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT

      # Step 3: Run Dependency Review
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ steps.default-branch.outputs.default_branch }} # Compare with the default branch
          head-ref: ${{ github.ref_name }} # Current branch
          comment-summary-in-pr: always # Add a comment to the PR with a summary of the findings
          # fail-on-severity: moderate # Uncomment to fail the workflow if vulnerabilities of a certain severity are found
          # deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later # Uncomment to block specific licenses
          # retry-on-snapshot-warnings: true # Uncomment to retry on snapshot warnings
